### ISSUE TITLE
com.geccocrawler.gecco.pipeline.PipelineFactory' that could not be found.

### ISSUE THREAD

**Issue by wilddylan** [xtuhcy/gecco-spring#2]
***************************
APPLICATION FAILED TO START
***************************

Description:

A component required a bean of type 'com.geccocrawler.gecco.pipeline.PipelineFactory' that could not be found.

Action:

Consider defining a bean of type 'com.geccocrawler.gecco.pipeline.PipelineFactory' in your configuration.

![image](https://user-images.githubusercontent.com/2519544/34924635-882217da-f9df-11e7-885e-627b645f3150.png)

![image](https://user-images.githubusercontent.com/2519544/34924750-44708d54-f9e0-11e7-8d8e-41701345776a.png)

**Comment by xtuhcy** [comment]
gecco-spring 的test能跑通吗？

**Comment by wilddylan** [comment]
test没有尝试，您那里没问题是吧？

**Comment by wilddylan** [comment]
我等下试试

**Comment by wilddylan** [comment]
你好，找到问题了，正式使用，因为 spring-boot可能配置 componentScan，所以要确保你的 beanConfigure 被扫描到

```
@ComponentScan({"meta", "com.geccocrawler.gecco.spring"})
```
这样就解决了问题。
