### ISSUE TITLE
我想把它做成一个方法，传一个参数进入，调用一次，爬一次数据，请求有什么好的途径没

### ISSUE THREAD

**Issue by WizWild** [xtuhcy/gecco-spring#4]
我现在是使用 
`geccoEngine.start(hash)
                .run();`
来实现的，但是这样，每次都会创建一个实例。多谢解答，谢谢！

**Comment by xtuhcy** [comment]
loop=false 使用 .run() 。定义一个全局变量，pipeline将爬出的结果保存到全局变量中

在 2019-05-12 23:08:40，"yyicon" <notifications@github.com> 写道：


我现在是使用
geccoEngine.start(hash) .run();
来实现的，但是这样，每次都会创建一个实例。多谢解答，谢谢！

**Comment by WizWild** [comment]
好的，感谢，我使用的队列，每次爬完一个页面，又从队列拿出来爬下一个
